import { chromium } from "@playwright/test";
const SP = process.argv[2];
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 1000 } })).newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(String(e).slice(0, 300)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); });
await page.goto("http://localhost:3000/login", { waitUntil: "networkidle" });
await page.fill("#email", "member@nsalgo.dev");
await page.fill("#password", "Northstar-2026!");
await Promise.all([page.waitForURL(/dashboard/), page.click("main form button:not([type=button])")]);
await page.goto("http://localhost:3000/dashboard/atlas", { waitUntil: "networkidle" });
await page.locator("section button").filter({ hasText: "#1" }).first().click();
await page.waitForTimeout(2500);
await page.screenshot({ path: `${SP}/drawer_0.png` });
await page.getByRole("tab", { name: "Options" }).click();
await page.waitForTimeout(500);
await page.locator("[role=dialog] .overflow-y-auto").evaluate((el) => el.scrollTo(0, 700));
await page.waitForTimeout(500);
await page.screenshot({ path: `${SP}/drawer_1.png` });
// search palette
await page.keyboard.press("Escape");
await page.keyboard.press("Control+k");
await page.keyboard.type("nvidia");
await page.waitForTimeout(1500);
await page.screenshot({ path: `${SP}/search_0.png` });
console.log("errors", JSON.stringify(errors));
await browser.close();
