import { CalendarClock } from "lucide-react";
import type { Metadata } from "next";
import { RegimePanel } from "@/components/atlas/regime-panel";
import { MembershipGate } from "@/components/member/membership-gate";
import { MemberBody } from "@/components/member/page-header";
import { Badge } from "@/components/ui/badge";
import { Panel, PanelBody, PanelHeader } from "@/components/ui/panel";
import { SCORE_DISCLAIMER } from "@/config/atlas";
import { AtlasHeaderStrip } from "@/features/atlas/header-strip";
import { AtlasSubnav } from "@/features/atlas/atlas-subnav";
import { SetupBoard } from "@/features/atlas/setup-board";
import { getMarketContext, marketBrief, scan } from "@/services/atlas/engine";
import { getMarketStatus } from "@/services/market";
import { getViewer } from "@/services/membership";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Atlas" };

export default async function AtlasOverviewPage() {
  const viewer = await getViewer();
  if (!viewer.paid) return <MembershipGate feature="ATLAS" description="ATLAS ranks day-trade and swing setups across sixteen factors and explains every ranking — with levels, options structures and risks." />;
  const [ctx, status, day, swing, brief] = await Promise.all([getMarketContext(), getMarketStatus(), scan("day"), scan("swing"), marketBrief()]);
  const top = [...day.setups, ...swing.setups].sort((a, b) => b.score.value - a.score.value);
  return (
    <>
      <AtlasHeaderStrip ctx={ctx} status={status.ok ? status.data : null} />
      <AtlasSubnav />
      <MemberBody>
        <div className="grid gap-6 2xl:grid-cols-[minmax(0,1fr)_380px]">
          <section className="min-w-0 space-y-4">
            <div className="flex flex-wrap items-end justify-between gap-2">
              <div>
                <h2 className="font-mono text-[11px] tracking-[0.28em] text-steel-200">TODAY&apos;S TOP SETUPS</h2>
                <p className="mt-1 text-[12px] text-steel-500">
                  {top.length} setups above threshold from {swing.evaluated} symbols · day {day.setups.length} · swing {swing.setups.length} · config {swing.configVersion}
                </p>
              </div>
              <p className="max-w-md text-[11px] leading-snug text-steel-500">{SCORE_DISCLAIMER}</p>
            </div>
            <SetupBoard setups={top} />
          </section>
          <aside className="space-y-4">
            <RegimePanel regime={ctx.regime} />
            <Panel>
              <PanelHeader eyebrow="AI market summary" title={brief.narrative.headline} actions={<Badge size="sm" variant="accent">AI</Badge>} />
              <PanelBody>
                <p className="text-[13px] leading-relaxed text-steel-300">{brief.narrative.summary}</p>
                {brief.narrative.watch.length ? (
                  <ul className="mt-4 space-y-1.5 text-[12.5px] text-steel-200">
                    {brief.narrative.watch.map((w) => (
                      <li key={w} className="flex gap-2">
                        <CalendarClock className="mt-0.5 size-3.5 shrink-0 text-steel-500" /> {w}
                      </li>
                    ))}
                  </ul>
                ) : null}
                <p className="mt-4 text-[10.5px] text-steel-500">Generated by {brief.generatedBy} from structured inputs. May contain errors.</p>
              </PanelBody>
            </Panel>
          </aside>
        </div>
      </MemberBody>
    </>
  );
}
