/** Market concepts searchable from global search; each links to an education article or the library. */
export const GLOSSARY: { term: string; aliases: string[]; summary: string; slug?: string }[] = [
  { term: "ATLAS score", aliases: ["score", "atlas", "ranking"], summary: "0–100 ranking of how strongly current data aligns with a setup's criteria.", slug: "reading-the-atlas-score" },
  { term: "Invalidation level", aliases: ["stop", "stop loss", "invalidation"], summary: "The price at which a setup's reasoning no longer holds.", slug: "invalidation-first" },
  { term: "Delta", aliases: ["greeks"], summary: "Option price sensitivity to a $1 move in the underlying.", slug: "options-greeks-in-practice" },
  { term: "Gamma", aliases: ["greeks"], summary: "Rate of change of delta.", slug: "options-greeks-in-practice" },
  { term: "Theta", aliases: ["time decay"], summary: "Daily option value decay, all else equal.", slug: "options-greeks-in-practice" },
  { term: "Vega", aliases: ["volatility sensitivity"], summary: "Option price sensitivity to implied volatility.", slug: "options-greeks-in-practice" },
  { term: "IV rank", aliases: ["implied volatility rank", "ivr"], summary: "Current implied volatility within its 52-week range.", slug: "iv-rank-and-structure" },
  { term: "Implied volatility", aliases: ["iv"], summary: "The volatility level implied by option prices.", slug: "iv-rank-and-structure" },
  { term: "Debit spread", aliases: ["vertical", "call debit spread", "put debit spread"], summary: "Buy one option, sell a further OTM option; defined risk.", slug: "debit-vs-credit-spreads" },
  { term: "Credit spread", aliases: ["vertical", "put credit spread", "call credit spread"], summary: "Sell one option, buy protection further OTM; collect a credit.", slug: "debit-vs-credit-spreads" },
  { term: "ATR", aliases: ["average true range", "volatility"], summary: "Typical daily range including gaps.", slug: "position-sizing-with-atr" },
  { term: "VWAP", aliases: ["volume weighted average price"], summary: "Session average price weighted by volume.", slug: "vwap-for-intraday-context" },
  { term: "Market regime", aliases: ["risk-on", "risk-off", "regime"], summary: "Classification of the broad tape from trend, volatility and breadth.", slug: "market-regimes-explained" },
  { term: "Market breadth", aliases: ["advance decline", "breadth"], summary: "How many stocks participate in a move.", slug: "breadth-and-participation" },
  { term: "FOMC", aliases: ["fed", "federal reserve", "rate decision"], summary: "Federal Open Market Committee policy decisions.", slug: "reading-fomc-days" },
  { term: "Form 4", aliases: ["insider", "section 16"], summary: "SEC filing reporting an insider's transaction within two business days.", slug: "public-disclosures-guide" },
  { term: "13F", aliases: ["institutional holdings", "whales"], summary: "Quarterly holdings report from large institutional managers.", slug: "public-disclosures-guide" },
  { term: "Periodic Transaction Report", aliases: ["congress", "stock act", "ptr"], summary: "STOCK Act disclosure of a member of Congress's securities transactions.", slug: "public-disclosures-guide" },
  { term: "Relative strength", aliases: ["rs", "outperformance"], summary: "Performance relative to a benchmark such as the S&P 500.", slug: "swing-trading-framework" },
  { term: "Sweep", aliases: ["options sweep", "flow"], summary: "An order routed across multiple exchanges to fill quickly; classification depends on the data provider." },
  { term: "Block trade", aliases: ["block"], summary: "A single large negotiated print." },
  { term: "Open interest", aliases: ["oi"], summary: "Number of outstanding option contracts." },
];
