import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Disclaimer", description: "Important information about NSALGO market data, AI-generated analysis and the limits of informational content.", alternates: { canonical: "/disclaimer" } };

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      updated="September 1, 2026"
      intro="NSALGO is a financial information and analytics platform. Please read this disclaimer before relying on anything you see here."
      sections={[
        { h: "Informational purposes only", body: <p>All content on NSALGO — including market data, ATLAS scores and setups, options analytics, news, disclosures, commentary and education — is provided for informational and educational purposes only.</p> },
        { h: "Not investment advice", body: <p>Nothing on NSALGO constitutes individualized investment, financial, legal or tax advice, a recommendation, an offer, or a solicitation to buy or sell any security or derivative. NSALGO is not a broker-dealer or registered investment adviser. Consider consulting a licensed professional before making investment decisions.</p> },
        { h: "No guarantee of performance", body: <><p>ATLAS scores are analytical rankings of how well current data aligns with defined criteria. They are not probabilities, predictions or guarantees. Entry zones, targets and invalidation levels describe a risk framework, not an expected outcome.</p><p>Past setups and their outcomes do not indicate future results. Trading securities and options involves substantial risk, including the loss of more than your initial investment in some strategies.</p></> },
        { h: "Market data", body: <p>Market data is sourced from third-party providers and may be delayed depending on provider and exchange licensing. Each module indicates whether data is live, delayed or end-of-day. Data may contain errors or omissions. In development environments NSALGO may display clearly labelled simulated data, which is not market data.</p> },
        { h: "AI-generated analysis", body: <p>Some explanations and summaries are generated by AI models from structured data computed by NSALGO. AI output may contain errors or omissions. NSALGO checks numeric statements against their source data, but you should verify any information that matters to your decisions.</p> },
        { h: "Public disclosures", body: <p>Insider, institutional and congressional disclosures are displayed as reported in public filings or by licensed aggregators, with links to source documents where available. A disclosure records that a transaction occurred. It does not establish the reason for the transaction and does not imply any wrongdoing by the individual or entity involved.</p> },
        { h: "Your responsibility", body: <p>You are solely responsible for your investment decisions and for evaluating the risks involved. NSALGO is not liable for losses arising from the use of, or reliance on, information provided on the platform.</p> },
      ]}
    />
  );
}
